### ISSUE TITLE
question

### ISSUE THREAD

**Issue by imthecheeser** [mtfy/Intelify#2]
sup im kinda new to this osint stuff and to mysql and i just wanted to ask how i can get 
"MYSQL_DATABASE"
and "OSINT_LOOKUP_TABLE_NAME" for the .env file
or maybe just like some explanation about what those two things do

**Comment by imthecheeser** [comment]
nvm i just asked chatgpt

**Comment by mtfy** [comment]
Hey @imthecheeser,
I՚m glad you had this resolved already.



In the `.env` file you are supposed to define your MySQL database credentials.

- `OSINT_LOOKUP_TABLE_NAME` ─ Name of the table where you imported [structure.sql](https://github.com/mtfy/Intelify/blob/main/structure.sql) to
- `MYSQL_HOST` ─ `127.0.0.1` or `localhost` if your database is not stored in external server
- `MYSQL_PORT` ─ `3306` unless manually changed
- `MYSQL_DATABASE` ─ Name of your database
- `MYSQL_USERNAME` ─ Username of your MySQL account that has the necessary priviliges in the database
- `MYSQL_PASSWORD` ─ Password for the MySQL acccount


Please note the values for `MYSQL_USERNAME`, `MYSQL_DATABASE`, and `MYSQL_PASSWORD` are supposed to be encoded using base64. See the example below.

`MYSQL_USERNAME=cm9vdA==`
`MYSQL_DATABASE=aW50ZWxpZnk=`
`MYSQL_PASSWORD=WW91clN1cGVyU3Ryb25nUGFzc3dk`
